config/routes.rb
Reddlr::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :posts do
    member do
      get 'comments'
      get 'removal'
      get 'pay'
      get 'execute'
    end
    collection do
      get 'complete'
    end
  end
  resources :subreddits do
    member do
      get 'stylesheet'
      get 'javascript'
    end
  end
  root 'subreddits#index'
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id              :integer          not null, primary key
#  reddit_id       :string(255)      not null
#  title           :string(255)      not null
#  sub_id          :integer          not null
#  tumblr_id       :string(255)
#  content_type_id :integer
#  submitted_at    :datetime
#  created_at      :datetime
#  updated_at      :datetime
#  json            :hstore
#  whitelist_id    :integer
#  garbage         :boolean
#  processed_at    :datetime
#  response        :hstore
#

require 'json'
class Post < ActiveRecord::Base
  acts_as_taggable
  belongs_to :sub
  belongs_to :whitelist
  belongs_to :content_type
  validates :reddit_id, uniqueness: true

  scope :random_queue, -> { where(submitted_at: nil).where.not(content_type_id: nil).order('RANDOM()') }
  scope :queue, -> { where(submitted_at: nil).where.not(content_type_id: nil).order(:created_at) }
  scope :successful, -> { where.not(tumblr_id: nil, submitted_at: nil) }
  scope :failed, -> { where(tumblr_id: nil).where.not(submitted_at: nil) }
  scope :garbage, -> { where(garbage: true) }

  # Filter out reddit self posts from the start
  before_save :check_if_self_post, :check_content_type, :check_whitelist

  def check_if_self_post
    if self.json['is_self'] == 'true' || self.json['is_self'] == true
      self.garbage = true
    end
  end

  def check_content_type
    ContentType.all.each do |ct|
      regex = Regexp.new ct.url_match
      self.content_type_id = ct.id if regex.match(self.json['url'])
    end
  end

  def check_whitelist
    if whitelist = Whitelist.find_by(domain: self.json['domain'])
      regex = Regexp.new whitelist.url_match
      self.whitelist_id = whitelist.id if whitelist.url_match && regex.match(self.json['url'])
    end
  end

  def remove
    api_key = ApiKey.where(enabled: true).order(:updated_at).first
    client = api_key.tumblr_client
    if client.delete(self.tumblr_subdomain, self.tumblr_id)
      self.update_attribute(:removed_at, Time.now)
    end
  end

  def url
    self.json['url']
  end

  def source
    "http://reddit.com#{self.json['permalink']}"
  end

  def reddit_url
    "http://reddlr.com/posts/#{self.reddit_id}/comments"
  end

  def post_title
    self.title
  end

  def tumblr_subdomain
    "reddlr-#{self.sub.name.downcase}.tumblr.com"
  end

end

app/controllers/posts_controller.rb
require 'paypal-sdk-rest'
include PayPal::SDK::REST

class PostsController < ApplicationController
  def comments
    post = Post.find_by(tummblr_id: params[:id])
    redirect_to post.source
  end

  def removal
    @post = Post.find_by(tumblr_id: params[:id])
  end

  def execute
    @post = Post.find_by(tumblr_id: params[:id])
    payment = Payment.find(session[:payment_id])
    if payment.execute(:payer_id => params[:PayerID])
      @post.remove
      redirect_to removal_post_path(@post.tumblr_id)
    else
      puts '-------------'
      puts 'PAYMENT ERROR'
      puts payment.error.inspect
      redirect_to removal_post_path(@post.tumblr_id), notice: 'Payment did not go through'
    end
  end

  def pay
    @post = Post.find_by(tumblr_id: params[:id])
    @payment = Payment.new(
        {
            :intent => "sale",
            :payer => {
                :payment_method => "paypal"
            },
            :redirect_urls => {
                :return_url => execute_post_url(@post.tumblr_id), #"http://8nsl.t.proxylocal.com/posts/#{@post.tumblr_id}/execute"
                :cancel_url => removal_post_url(@post.tumblr_id)
            },
            :transactions => [
                {
                    :item_list => {
                        :items => [
                            {
                                :name => "item",
                                :sku => "item",
                                :price => "1",
                                :currency => "USD",
                                :quantity => 1
                            }
                        ]
                    },
                    :amount => {
                        :total => "1.00",
                        :currency => "USD"
                    },
                    :description => "Remove Tumblr Post ##{@post.tumblr_id}"
                }
            ]
        }
    )
    if @payment.create
      session[:payment_id] = @payment.id
      payment = Payment.find(@payment.id)
      redirect_to payment.links[1].href
    else
      redirect_to removal_post_path(@post.tumblr_id), notice: 'Something went wrong!'
    end
  end
end

app/views/posts/removal.html.slim
h2 Content Removal Request
.jumbotron
  h2= @post.title
  p= "Tumblr ID: #{@post.tumblr_id}"
  p style="font-size: 11px"
    = "Source: #{@post.source}"

- if @post.removed_at
  .alert.alert-warning.text-center
    = "This post has been removed from tumblr on #{@post.removed_at}"

- else
  .row
    .col-lg-12
      h4 Notice:
      .alert.alert-info
        | If you own the rights to the content and you submitted the content to reddit.com, reddlr has <strong>ZERO</strong> legal obligation to remove this content.
        a href="http://www.reddit.com/help/useragreement#p_18"  reddit TOS
        |  paragraph #18 clearly states:
      blockquote style="font-size: 12px;"
        | By submitting User Content to reddit, you grant us a royalty-free, perpetual, irrevocable, non-exclusive, unrestricted, worldwide license to reproduce, prepare derivative works, distribute copies, perform, or publicly display your User Content in any medium and for any purpose, including commercial purposes, <strong style="color: red;">and to authorize others to do so</strong>.

    .row.marketing
      .col-lg-6
        h4
          | Option #1 &nbsp;
          small Manual Request (FREE)
        p Send an takedown request to the webmaster and we'll try to get the content removed within 24 hours.
        p.text-center style="margin-top: 25px;"
          = link_to 'Send Request', 'https://andey.wufoo.com/forms/z10h91it1ovk64n/', class: 'btn btn-primary'


      .col-lg-6
        h4
          | Option #2 &nbsp;
          small Instant Removal ($1 USD)
        p style="margin-bottom: 25px;" Delete the tumblr post instantly after a payment of $1.00. The one dollar fee is to prevent automatic malicious content deletion.
        p.text-center
          = link_to (image_tag 'paypal_buynow.gif'), pay_post_path(@post.tumblr_id)